dubbo:
  application:
    name: rmi-provider
  protocol:
    port: 30880
    name: rmi
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.study.dubbo.protocol.rmi

logging:
  level:
    com.study: debug