dubbo:
  application:
    name: broadcast-provider
  protocol:
    port: 30882
    name: dubbo
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.study.dubbo.failover.broadcast

logging:
  level:
    com.study: debug