dubbo:
  application:
    name: simple-provider
  protocol:
    port: 30880
    name: dubbo
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.study.dubbo.protocol.simple
  config-center:
    address: zookeeper://127.0.0.1:2181

logging:
  level:
    com.study: debug