dubbo:
  application:
    name: thread-model-provider
  protocol:
    port: 30880
    name: dubbo
    dispatcher: message
    threadpool: cached
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.study.dubbo.threadmodel
logging:
  level:
    com.study: debug
    org.apache.dubbo: debug

server:
  port: 8082

