dubbo:
  application:
    name: kryo-provider
  protocol:
    port: 30880
    name: dubbo
    serialization: kryo
    optimizer: com.study.dubbo.serialization.kryo.SerializationOptimizerImpl
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.study.dubbo.serialization.kryo

logging:
  level:
    com.study: debug