dubbo:
  application:
    name: mock-provider
  protocol:
    port: 30880
    name: dubbo
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.study.dubbo.mock

logging:
  level:
    com.study: debug