dubbo:
  application:
    name: hash-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
server:
  port: 8081